spring:
  devtools:
    livereload:
      enabled: true
  jpa:
    show-sql: true
  config:
    import:
      - classpath:/application-oauth2.yml
      - classpath:/application-datasource.yml
server:
  port: 80
